services:
  - type: web
    name: volatix-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run src/streamlit_app/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
